version: '3.1'
services:
  mongoContainer:
    image: 'mongo'
    container_name: 'mongo-db-container'
    volumes:
      - mongoData:/data/db
    networks:
      - default
    ports:
      - 27017:27017

  product-service:
    build: ./
    image: product-service
    depends_on:
      - mongoContainer
    networks:
      - default
    restart: always
    ports:
      - 8080:8080

volumes:
  mongoData:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.103.0.1/16