version: '3.1'
services:
  mongoContainer:
    image: 'mongo'
    container_name: 'mongo-db-container'
    volumes:
      - mongoData:/data/db
    network_mode: host
    ports:
      - 27017:27017

  product-service:
    build: ./
    image: product-service
    depends_on:
      - mongoContainer
    network_mode: host
    restart: always
    ports:
      - 8080:8080

volumes:
  mongoData: